# Generated by Django 5.2.12 on 2026-03-12 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FyersAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100)),
                ('secret_key', models.CharField(max_length=200)),
                ('redirect_uri', models.CharField(max_length=200)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('token_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='client_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='accesstoken',
            index=models.Index(fields=['client_id', 'token_date'], name='accounts_ac_client__188941_idx'),
        ),
        migrations.AddField(
            model_name='fyersaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
