# Generated by Django 4.2.29 on 2026-03-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_fyersaccount_alter_accesstoken_client_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BhavcopyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, unique=True)),
                ('trade_date', models.DateField()),
                ('year', models.IntegerField()),
                ('month', models.CharField(max_length=10)),
                ('file_data', models.BinaryField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, unique=True)),
                ('trade_date', models.DateField(null=True)),
                ('week_day', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
                ('download_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('file_data', models.BinaryField()),
            ],
        ),
    ]
