# Generated by Django 4.2.29 on 2026-03-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_bhavcopyfile_downloadlog_generatedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bhavcopyfile',
            name='file_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='downloadlog',
            name='download_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='downloadlog',
            name='file_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='downloadlog',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='downloadlog',
            name='trade_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generatedfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='generatedfile',
            name='file_name',
            field=models.CharField(max_length=200),
        ),
    ]
