# Generated by Django 4.2.29 on 2026-03-17 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_bhavcopyfile_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadlog',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
