# Generated by Django 4.2.29 on 2026-03-17 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_downloadlog_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadlog',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='downloadlog',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
