# Generated by Django 4.2.29 on 2026-03-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_downloadlog_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadlog',
            name='file_name',
            field=models.CharField(max_length=200),
        ),
    ]
