# Generated by Django 4.2.29 on 2026-03-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_onemindatafile'),
    ]

    operations = [
        migrations.AddField(
            model_name='onemindatafile',
            name='file_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
